[package]
name = "starknet-mutation-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
colored = "2.1.0"
rayon = "1.10.0"

[dev-dependencies]
rstest = "0.21.0"
