name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Installing nightly
      run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
    - name: Run format
      run: cargo +nightly fmt --check 
